name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:



  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        ports:
          -5432:5432
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: mysecretpassword
<<<<<<< HEAD
=======
          POSTGRES_USER: postgres
>>>>>>> origin/main
          POSTGRES_DB: rsmstore
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_ready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: make test
